Add missing neon f32 instructions
exo-lang/exo pull request #358
Opened 2023-03-14 03:09 UTC by yamaguchi1024

2023-03-14 03:43 UTC, SamirDroubi commented on src/exo/platforms/neon.py
> +def neon_broadcast_4xf32_scaler(dst: [f32][4] @ Neon4f, src: f32 @ DRAM):
Typo: scalar

2023-03-14 03:43 UTC, SamirDroubi commented on src/exo/platforms/neon.py
> +#      better way of handling aliasing
I am unsure if this is only useful as a hack due to aliasing. I could imagine this pattern showing up when you are doing more automation.

2023-03-14 15:24 UTC, alexreinking requested changes
looks good, but fix typo

2023-03-22 19:51 UTC, alexreinking approved these changes

2023-03-22 20:22 UTC, merged