Precision propagation bug fix
exo-lang/exo pull request #519
Opened 2023-10-18 15:45 UTC by andrewj31415

2023-10-18 15:46 UTC, andrewj31415 commented
@SamirDroubi @skeqiqevian

2023-10-19 03:32 UTC, yamaguchi1024 requested changes

2023-10-19 03:32 UTC, yamaguchi1024 commented on apps/blur/blur/blur.d
> +  /Users/keqian/.venv/exo/lib/python3.9/site-packages/asdl_adt/__init__.py \
Can you remove this file from the PR?

2023-10-19 05:03 UTC, skeqiqevian commented on apps/blur/blur/blur.d
> +  /Users/keqian/.venv/exo/lib/python3.9/site-packages/asdl_adt/__init__.py \
oops done

2023-10-19 17:24 UTC, merged