Fix bug in inline_assign safety check
exo-lang/exo pull request #566
Opened 2024-01-31 21:46 UTC by SamirDroubi

* We cannot allow inlining an assign if some buffer in the rhs is read, but also written at some point after the assignment.

2024-01-31 22:07 UTC, yamaguchi1024 approved these changes

2024-02-01 14:17 UTC, SamirDroubi commented
When I made these checks too strict, it caused some usages to no longer work in BLAS. I will rewrite the safety check for this operation to make it as exact as possible. There is another bug I discovered in its implementation which I will also fix.

2024-04-06 16:40 UTC, yamaguchi1024 requested changes
I think the correct thing to do here is not to "prohibit users from doing inline_assign when the expression is written at some point,"  but to "not delete the assign statement when the expression is written." So that it preserves the output behaviour.

2024-06-04 00:46 UTC, yamaguchi1024 commented
Closing, this and #612 needs to be fixed properly at some point

2024-06-04 00:46 UTC, closed without merging