Add type inference for constants
exo-lang/exo pull request #581
Opened 2024-02-21 19:45 UTC by kehemo

not working yet, need major changes

2024-02-26 16:23 UTC, yamaguchi1024 requested changes

2024-02-26 16:23 UTC, yamaguchi1024 commented on .gitignore
> +scratch/
remove this line

2024-02-26 16:23 UTC, yamaguchi1024 commented on tests/golden/test_window/test_window_stmt.txt
> +for (int_fast32_t i = ((int_fast32_t) 0); i < n; i++) {
Remove the casting for index expressions

2024-02-26 16:23 UTC, yamaguchi1024 commented on tests/test_codegen.py
> +    assert x[0] == 16777216
We need individual tests for different buffer types, e.g., 
a : i8
a + 3

2024-02-26 16:53 UTC, yamaguchi1024 commented on src/exo/typecheck.py
> -            elif e.op == "and" or e.op == "or":
Change check_e to `check_e(e, is_index=False)`

2024-02-26 16:54 UTC, yamaguchi1024 commented on src/exo/typecheck.py
> -                    self.err(lhs, "expected 'bool' argument to logical op")
```
if is_index:
   ty = {float: T.R, bool: T.bool, int: T.int}.get(type(e.val))
else:
   ty = {float: T.R, bool: T.bool, int: T.R}.get(type(e.val))
```

2024-02-26 17:00 UTC, yamaguchi1024 commented on src/exo/LoopIR_compiler.py
> +            return f"(({e.type.ctype()}) {str(e.val)})"
```
if e.is_indexable():
    return str(e.val)
else:
   if e.base_typ() == T.f32:
     return str(e.val)+'f'
   if e.base_typ() == T.f64 or e.base_typ() == T.i32:
      return str(e.val)
   return f"(({e.type.ctype()}) {str(e.val)})"
```

2024-02-28 19:48 UTC, kehemo commented
BLAS macos-14 testing check appeared to fail first time due to nondeterministic error in formatter
[https://github.com/google/yapf/issues/1164](https://github.com/google/yapf/issues/1164)

2024-02-28 23:19 UTC, yamaguchi1024 commented on src/exo/LoopIR_compiler.py
> +                return f"{float(e.val)}"
Why do you cast to float when T.f64? It could underflow, right?

2024-02-28 23:19 UTC, yamaguchi1024 commented on src/exo/LoopIR_compiler.py
> +                return f"{float(e.val)}"
Oh it's Python float, nvm

2024-02-28 23:26 UTC, yamaguchi1024 approved these changes
Looks good to me! Please write a commit message when you merge

2024-02-28 23:42 UTC, merged